import 'package:equatable/equatable.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:jeb/core/constants/app_constants.dart';
import 'package:jeb/core/usecase/usecase.dart';
import 'package:jeb/features/accounts/domain/entities/account.dart';
import 'package:jeb/features/accounts/domain/usecases/accounts_usecases.dart';
import 'package:jeb/features/recurring/domain/entities/recurrence_frequency.dart';
import 'package:jeb/features/recurring/domain/entities/recurring_transaction.dart';
import 'package:jeb/features/recurring/domain/usecases/delete_recurring_transaction.dart';
import 'package:jeb/features/recurring/domain/usecases/save_recurring_transaction.dart';
import 'package:jeb/features/transactions/domain/entities/transaction.dart';
import 'package:jeb/features/transactions/domain/entities/transaction_type.dart';
import 'package:jeb/features/transactions/domain/usecases/add_transaction.dart';
import 'package:uuid/uuid.dart';

part 'add_transaction_state.dart';

/// Holds the add/edit form state. Saves either a one-off [Transaction] or, when
/// [AddTransactionState.repeat] is on, a [RecurringTransaction] rule whose
/// occurrences are generated by the materializer.
class AddTransactionCubit extends Cubit<AddTransactionState> {
  AddTransactionCubit({
    required AddTransaction addTransaction,
    required SaveRecurringTransaction saveRecurringTransaction,
    required DeleteRecurringTransaction deleteRecurringTransaction,
    required GetAccounts getAccounts,
    required Uuid uuid,
  })  : _addTransaction = addTransaction,
        _saveRecurringTransaction = saveRecurringTransaction,
        _deleteRecurringTransaction = deleteRecurringTransaction,
        _getAccounts = getAccounts,
        _uuid = uuid,
        super(AddTransactionState(date: DateTime.now()));

  final AddTransaction _addTransaction;
  final SaveRecurringTransaction _saveRecurringTransaction;
  final DeleteRecurringTransaction _deleteRecurringTransaction;
  final GetAccounts _getAccounts;
  final Uuid _uuid;

  /// Seed the form — either blank (with the user's default currency) or
  /// pre-filled from an [existing] transaction for editing.
  void initialize({Transaction? existing, required String defaultCurrency}) {
    if (existing == null) {
      emit(AddTransactionState(date: DateTime.now(), currencyCode: defaultCurrency));
      return;
    }
    emit(
      AddTransactionState(
        date: existing.date,
        amount: existing.amount,
        type: existing.type,
        selectedCategoryId: existing.categoryId,
        note: existing.note ?? '',
        currencyCode: existing.currencyCode,
        editingId: existing.id,
        recurringId: existing.recurringId,
        receiptPath: existing.receiptPath,
        accountId: existing.accountId,
        accounts: state.accounts,
      ),
    );
  }

  /// Loads the user's accounts so the form can offer an account picker. Safe to
  /// call before or after [initialize]; merges into the current state.
  Future<void> loadAccounts() async {
    final result = await _getAccounts(const NoParams());
    if (isClosed) return;
    final List<Account> accounts =
        result.fold((_) => const <Account>[], (List<Account> a) => a);
    emit(state.copyWith(accounts: accounts));
  }

  void accountSelected(String? accountId) => emit(
        accountId == null
            ? state.copyWith(clearAccount: true)
            : state.copyWith(accountId: accountId),
      );

  void amountChanged(double amount) =>
      emit(state.copyWith(amount: amount, status: AddTransactionStatus.editing));

  void typeChanged(TransactionType type) =>
      emit(state.copyWith(type: type, clearCategory: true));

  void categorySelected(String categoryId) =>
      emit(state.copyWith(selectedCategoryId: categoryId));

  void currencyChanged(String currencyCode) =>
      emit(state.copyWith(currencyCode: currencyCode));

  void noteChanged(String note) => emit(state.copyWith(note: note));

  void dateChanged(DateTime date) => emit(state.copyWith(date: date));

  void repeatChanged(bool repeat) => emit(state.copyWith(repeat: repeat));

  void frequencyChanged(RecurrenceFrequency frequency) =>
      emit(state.copyWith(frequency: frequency));

  void endDateChanged(DateTime? endDate) => emit(
        endDate == null
            ? state.copyWith(clearEndDate: true)
            : state.copyWith(endDate: endDate),
      );

  void receiptAttached(String relativePath) =>
      emit(state.copyWith(receiptPath: relativePath));

  void receiptRemoved() => emit(state.copyWith(clearReceipt: true));

  Future<void> submit() async {
    if (!state.canSubmit || state.isSubmitting) return;
    emit(state.copyWith(status: AddTransactionStatus.submitting));

    final result = state.repeat && !state.isEditing
        ? await _saveRecurringTransaction(_buildRule())
        : await _addTransaction(_buildTransaction());
    if (isClosed) return;

    result.fold(
      (failure) => emit(
        state.copyWith(
          status: AddTransactionStatus.failure,
          errorMessage: failure.message,
        ),
      ),
      (_) => emit(state.copyWith(status: AddTransactionStatus.success)),
    );
  }

  /// Stops a recurring series (deletes the rule). Already-generated
  /// transactions are kept. Only valid when editing a recurring occurrence.
  Future<void> stopRecurring() async {
    final String? ruleId = state.recurringId;
    if (ruleId == null || state.isSubmitting) return;
    emit(state.copyWith(status: AddTransactionStatus.submitting));
    final result = await _deleteRecurringTransaction(ruleId);
    if (isClosed) return;
    result.fold(
      (failure) => emit(
        state.copyWith(
          status: AddTransactionStatus.failure,
          errorMessage: failure.message,
        ),
      ),
      (_) => emit(state.copyWith(status: AddTransactionStatus.success)),
    );
  }

  Transaction _buildTransaction() => Transaction(
        id: state.editingId ?? _uuid.v4(),
        amount: state.amount,
        currencyCode: state.currencyCode,
        categoryId: state.selectedCategoryId!,
        date: state.date,
        type: state.type,
        note: state.note.trim().isEmpty ? null : state.note.trim(),
        recurringId: state.recurringId,
        receiptPath: state.receiptPath,
        accountId: state.accountId,
      );

  RecurringTransaction _buildRule() {
    final DateTime start =
        DateTime(state.date.year, state.date.month, state.date.day);
    return RecurringTransaction(
      id: _uuid.v4(),
      amount: state.amount,
      currencyCode: state.currencyCode,
      categoryId: state.selectedCategoryId!,
      type: state.type,
      frequency: state.frequency,
      startDate: start,
      nextDueDate: start,
      endDate: state.endDate,
      note: state.note.trim().isEmpty ? null : state.note.trim(),
    );
  }
}
