part of 'add_transaction_cubit.dart';

enum AddTransactionStatus { editing, submitting, success, failure }

final class AddTransactionState extends Equatable {
  const AddTransactionState({
    required this.date,
    this.amount = 0,
    this.type = TransactionType.expense,
    this.selectedCategoryId,
    this.note = '',
    this.currencyCode = AppConstants.defaultCurrencyCode,
    this.editingId,
    this.recurringId,
    this.receiptPath,
    this.repeat = false,
    this.frequency = RecurrenceFrequency.monthly,
    this.endDate,
    this.status = AddTransactionStatus.editing,
    this.errorMessage,
  });

  final double amount;
  final TransactionType type;
  final String? selectedCategoryId;
  final String note;
  final String currencyCode;
  final String? editingId;

  /// Set when editing a transaction that was generated by a recurring rule;
  /// preserved on save and used to offer "Stop recurring".
  final String? recurringId;

  /// Relative path of an attached receipt photo, or null.
  final String? receiptPath;

  bool get hasReceipt => receiptPath != null;

  /// When creating a new transaction, whether it should become a recurring
  /// rule. [date] doubles as the rule's start date.
  final bool repeat;
  final RecurrenceFrequency frequency;
  final DateTime? endDate;

  final DateTime date;
  final AddTransactionStatus status;
  final String? errorMessage;

  bool get isEditing => editingId != null;

  /// Whether the transaction being edited is part of a recurring series.
  bool get isRecurringOccurrence => recurringId != null;

  bool get canSubmit => amount > 0 && selectedCategoryId != null;
  bool get isSubmitting => status == AddTransactionStatus.submitting;

  AddTransactionState copyWith({
    double? amount,
    TransactionType? type,
    String? selectedCategoryId,
    bool clearCategory = false,
    String? note,
    String? currencyCode,
    bool? repeat,
    RecurrenceFrequency? frequency,
    DateTime? endDate,
    bool clearEndDate = false,
    String? receiptPath,
    bool clearReceipt = false,
    DateTime? date,
    AddTransactionStatus? status,
    String? errorMessage,
  }) {
    return AddTransactionState(
      amount: amount ?? this.amount,
      type: type ?? this.type,
      selectedCategoryId:
          clearCategory ? null : (selectedCategoryId ?? this.selectedCategoryId),
      note: note ?? this.note,
      currencyCode: currencyCode ?? this.currencyCode,
      editingId: editingId,
      recurringId: recurringId,
      receiptPath: clearReceipt ? null : (receiptPath ?? this.receiptPath),
      repeat: repeat ?? this.repeat,
      frequency: frequency ?? this.frequency,
      endDate: clearEndDate ? null : (endDate ?? this.endDate),
      date: date ?? this.date,
      status: status ?? this.status,
      errorMessage: errorMessage,
    );
  }

  @override
  List<Object?> get props => [
        amount,
        type,
        selectedCategoryId,
        note,
        currencyCode,
        editingId,
        recurringId,
        receiptPath,
        repeat,
        frequency,
        endDate,
        date,
        status,
        errorMessage,
      ];
}
