/// Database schema constants — single source of truth for table/column names.
abstract final class DbConstants {
  const DbConstants._();

  static const String databaseName = 'jeb.db';
  static const int databaseVersion = 4;

  // Tables
  static const String transactionsTable = 'transactions';
  static const String categoriesTable = 'categories';
  static const String budgetsTable = 'budgets';
  static const String recurringTransactionsTable = 'recurring_transactions';

  // Recurring-transaction columns (reuses amount/currency/category/type/note)
  static const String columnFrequency = 'frequency';
  static const String columnStartDate = 'start_date';
  static const String columnNextDueDate = 'next_due_date';
  static const String columnEndDate = 'end_date';

  // Budget columns (id reused; overall budget keyed by [overallBudgetKey])
  static const String columnLimitAmount = 'limit_amount';
  static const String overallBudgetKey = '__overall__';

  // Shared columns
  static const String columnId = 'id';
  static const String columnUpdatedAt = 'updated_at';
  static const String columnIsDeleted = 'is_deleted';

  // Transaction columns
  static const String columnAmount = 'amount';
  static const String columnCurrencyCode = 'currency_code';
  static const String columnCategoryId = 'category_id';
  static const String columnNote = 'note';
  static const String columnDate = 'date';
  static const String columnType = 'type';

  /// Set on transactions generated by a recurring rule (the rule's id), so the
  /// UI can show a recurring badge. Null for one-off transactions.
  static const String columnRecurringId = 'recurring_id';

  // Category columns
  static const String columnName = 'name';
  static const String columnIconCodePoint = 'icon_code_point';
  static const String columnColorValue = 'color_value';
}
